# Generated by Django 4.2.30 on 2026-08-03 20:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('elevation_gain', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('expert', 'Expert')], default='easy', max_length=10)),
                ('is_open', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
