# Generated by Django 4.2.30 on 2026-08-06 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_park_trail_park'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trails', to='trails.park'),
        ),
    ]
